properties([
  parameters([
    string(name: 'CONTAINER_REGISTRY_SERVER', defaultValue: 'h2floh.azurecr.io'),
    string(name: 'CONTAINER_REGISTRY_JENKINS_CREDENTIALS', defaultValue: 'acr-h2floh-principal'),
  ])
])

pipeline {
    agent {
        docker {
            image "${params.CONTAINER_REGISTRY_SERVER}/devopsoh/netcore:build"
            args '-v /root/.m2:/root/.m2' 
        }
    }
    environment {
        CONTAINER_REG_CRED = credentials("${params.CONTAINER_REGISTRY_JENKINS_CREDENTIALS}")
        def REGISTRY_SERVER = "${params.CONTAINER_REGISTRY_SERVER}"
        def CONTAINER_IMAGE_NAME = 'devopsoh/api-poi'
        def CONTAINER_IMAGE_LABEL = "${env.BUILD_ID}"
        def WORKING_DIR = 'apis/poi/'
    }
    stages {
        stage('Build') { 
            steps {
                sh  'cd ${WORKING_DIR} && dotnet build' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd ${WORKING_DIR} && dotnet test'
            }
        }
        stage('DockerBuild') {
            steps {
                sh 'cd ${WORKING_DIR}/web && docker build . -t ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL} -t ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:latest'
            }
        }
        stage('DockerPush') {
            steps {
                sh 'docker login -p ${CONTAINER_REG_CRED_PSW} -u ${CONTAINER_REG_CRED_USR} ${REGISTRY_SERVER}'  
                sh 'docker push ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL}'
                sh 'docker push ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:latest'
            }
        }
    }
}