pipeline {
    agent {
        docker {
            //image 'maven:3-alpine' 
            image 'mavendocker:alpine'
            args '-v /root/.m2:/root/.m2' 
        }
    }
    environment {
        CONTAINER_REG_CRED = credentials('acr-h2floh-principal')
        def REGISTRY_SERVER = 'h2floh.azurecr.io'
        def CONTAINER_IMAGE_NAME = 'test/abc'
        def CONTAINER_IMAGE_LABEL = "${env.BUILD_ID}"
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd apis/user-java/ && mvn -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd apis/user-java/ && mvn test'
            }
            post {
                always {
                    junit 'apis/user-java/target/surefire-reports/*.xml'
                }
            }
        }
        stage('DockerBuild') {
            steps {
                sh 'cd apis/user-java/ && docker build . -t ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL}'
            }
        }
        stage('DockerPush') {
            steps {
                sh 'docker login -p ${CONTAINER_REG_CRED_PSW} -u ${CONTAINER_REG_CRED_USR} ${REGISTRY_SERVER}'  
                sh 'docker push ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL}'
            }
        }
    }
}