pipeline {
    agent {
        docker {
            //image 'maven:3-alpine' 
            image 'mavendocker:alpine'
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd apis/user-java/ && mvn -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd apis/user-java/ && mvn test'
            }
            post {
                always {
                    junit 'apis/user-java/target/surefire-reports/*.xml'
                }
            }
        }
        stage('DockerBuild') {
            steps {
                sh 'cd apis/user-java/ && docker build .'
            }
        }
    }
}