pipeline {
    agent {
        docker {
            image 'TODO image for GO BUILD & DOCKER'
            args '-v /root/.m2:/root/.m2' 
        }
    }
    environment {
        CONTAINER_REG_CRED = credentials('acr-h2floh-principal')
        def REGISTRY_SERVER = 'h2floh.azurecr.io'
        def CONTAINER_IMAGE_NAME = 'devopsoh/api-trip'
        def CONTAINER_IMAGE_LABEL = "${env.BUILD_ID}"
        def WORKING_DIR = 'apis/trips/'
    }
    stages {
        stage('Build') { 
            steps {
                sh  'cd ${WORKING_DIR} && TODO GO BUILD' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd ${WORKING_DIR} && TODO GO BUILD'
            }
            post {
                always {
                    //TODO Report Test for GO Jenkins 
                }
            }
        }
        stage('DockerBuild') {
            steps {
                sh 'cd ${WORKING_DIR} && docker build . -t ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL} -t ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:latest'
            }
        }
        stage('DockerPush') {
            steps {
                sh 'docker login -p ${CONTAINER_REG_CRED_PSW} -u ${CONTAINER_REG_CRED_USR} ${REGISTRY_SERVER}'  
                sh 'docker push ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:${CONTAINER_IMAGE_LABEL}'
                sh 'docker push ${REGISTRY_SERVER}/${CONTAINER_IMAGE_NAME}:latest'
            }
        }
    }
}